# This is a configuration file of wiskess that will run tools to process
# collections or mounted disks of Windows devices. It is built to run with 
# wiskess on a Linux-based device. 
# This includes the DLLs of EZTools which are executed with dotnet. Some 
# aren't supported in Linux such as SumECmd due to needing "ESI specific Windows libraries" 

wiskers:
  - name: consolehost_history
    binary: 'bash'
    args: -c "PSReadLine script was ran"
    outfolder: PSReadLine
    outfile: '*ConsoleHost_history.txt'
    input: consolehost_history
    github: 
    script: true
    script_posh: 'hist="{input}"
      outDir="{outfolder}"
      if [ -n "$hist" ]; then
        for file in "$hist"; do
          fn=$(rg -No "Users/(?P<user>.+?)/AppData" -r "${user}_ConsoleHost_history.txt" $file)
          cp $file "$outDir/$fn"
        done
      fi'
  - name: consolehost_history_py
    binary: '{tool_path}/venv/bin/python3'
    args: '{tool_path}/collect_powershell_history.py {input} {outfolder}'
    outfolder: PSReadLine
    outfile: '*ConsoleHost_history.txt'
    input: consolehost_history

reporters:
  - name: iocs_summary
    binary: rg
    args: '-aiwFf {ioc_file} {outfolder} --json > {outfolder}/{outfile}'
    outfolder: IOC_Findings
    outfile: IOCs_summary.json
    input: none
    github: https://github.com/BurntSushi/ripgrep.git

enrichers:
  - name: iocs_analysis
    binary: rg
    args: '--hidden --trim -zUiFf {ioc_file} {out_path} > {outfolder}/{outfile}'
    outfolder: IOC_Findings
    outfile: iocs_analysis.txt
    input: base
    github: https://github.com/BurntSushi/ripgrep.git
